<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWpf>true</UseWpf>
		<OutputType>Exe</OutputType>
		<RootNamespace>Flow.VSCodeWorkspaces.Cli</RootNamespace>
		<AssemblyName>vscode-workspaces</AssemblyName>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<LangVersion>latest</LangVersion>
		<Nullable>warnings</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Flow.Plugin.VSCodeWorkspaces.csproj" />
	</ItemGroup>
</Project>
